version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api/store:/store
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "bookz"
      POSTGRES_USER: "pooneh"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
